# name: remote ssh command

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using ssh key
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.LIGHTSAIL_HOST }}
#         username: ${{ secrets.LIGHTSAIL_USERNAME }}
#         key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
#         port: ${{ secrets.LIGHTSAIL_PORT }}
#         script: whoami
      

name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.LIGHTSAIL_HOST }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $TEST
