name: ssh git fetch  
on:
  push: 
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
        port: ${{ secrets.LIGHTSAIL_PORT }}
        script: |
          cd /home/admin-blog
          git fetch origin
          git merge origin/main
